netkit-rwho: Include stdint.h for int32_t
This ensures that when libc does not include stdint.h indirectly then it
still can compile

Fixes
| ../include/protocols/rwhod.h:57:2: error: unknown type name 'int32_t'; did you mean 'uint32_t'?

Signed-off-by: Khem Raj <raj.khem@gmail.com>